set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-kitty:RGB"

#Set prefix
set -g prefix C-Space

# Start windows at 1, not 0
set -g base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind v split-window -v -c "#{pane_current_path}"
bind b split-window -h -c "#{pane_current_path}"

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

#other
set -g status-position top
set -g mouse on
set -g set-clipboard on
set -g detach-on-destroy off

# remove default binding since replacing
unbind %
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugins 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'

#Theme
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "weather time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#S"
set -g @dracula-show-left-sep 
set -g @dracula-show-right-sep 
set -g @dracula-show-empty-plugins false
set -g @dracula-day-month true
set -g @dracula-show-timezone false
set -g @dracula-military-time true
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false

#Color
set -g @dracula-attached-clients-colors "cyan dark_gray"
set -g @dracula-weather-colors "dark_gray white"
set -g @dracula-time-colors "dark_gray white"
set -g @dracula-colors "
white='#DCD7BA'
gray='#1F1F28'
dark_gray='#17171E'
light_purple='#938AA9'
dark_purple='#17171E'
cyan='#8be9fd'
green='#76946A'
orange='#FFA066'
red='#C34043'
pink='#D27399'
yellow='#DCA561'
"

# Plugin settings
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

run '~/.dotfiles/tmux/plugins/tpm/tpm'
